
const ANIMALS = {

  "arnab": {
    name: "Arnab",
    scientific: "Oryctolagus",
    descriptionMY: "Arnab mempunyai deria pendengaran yang sangat tajam. Mereka boleh mengenal pasti dari mana datangnya setiap bunyi. Telinga mereka juga boleh berputar 180 darjah. Tidak seperti haiwan peliharaan lain, arnab tidak mengeluarkan sebarang bunyi. Malah, arnab berkomunikasi melalui pergerakan otot. Pergerakan ini juga sangat kecil dan sukar untuk dikesan.",
    descriptionEN: "Rabbits have a very sharp sense of hearing. They can identify where each sound is coming from. Their ears can also rotate 180 degrees. Unlike other pets, rabbits do not make any noise. In fact, rabbits communicate through muscle movements. This movement is also very small and difficult to detect.",
    life: "9 Tahun",
    group: "Mamalia",
    diet: "Sayur, Buah & Rumput",
    origin: "Asia",
    status: "Kurang Membimbangkan",
    fact: "Telinga arnab boleh berputar 180 darjah untuk mengesan bunyi dari mana-mana arah.",
    image: "Assets/Animals/arnab.jpg"
  },

  "musang-pulut": {
    name: "Musang Pulut",
    scientific: "Paradoxurus hermaphroditus",
    descriptionMY: "Musang Pulut, atau dikenali juga sebagai 'toddy cat', gemar meminum nira bunga pokok palma yang telah bertapai. Ia adalah haiwan nokturnal yang memanjat pokok dengan cekap untuk mencari buah-buahan masak. Musang ini turut memainkan peranan penting dalam menyebarkan biji benih di dalam hutan.",
    descriptionEN: "Musang Pulut, also called the toddy cat, gets its nickname from its habit of drinking fermented sap from palm flowers. It is a nocturnal, skilled climber that forages for ripe fruit at night. This civet plays an important role in seed dispersal across the forest.",
    life: "15-20 Tahun",
    group: "Mamalia",
    diet: "Buah-buahan & Haiwan Kecil",
    origin: "Asia Selatan & Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Ia dipanggil 'toddy cat' kerana gemar minum nira bunga palma yang bertapai.",
    image: "Assets/Animals/musang-pulut.jpg"
  },
  "musang-lamri": {
    name: "Musang Lamri",
    scientific: "Paguma larvata",
    descriptionMY: "Musang Lamri mudah dikenali menerusi corak topeng hitam-putih pada mukanya. Ia hidup di kawasan hutan yang luas merangkumi anak benua India hingga Asia Tenggara dan selatan China. Musang ini bersifat omnivor dan aktif pada waktu malam mencari buah serta haiwan kecil.",
    descriptionEN: "Musang Lamri is easily recognized by the black-and-white mask pattern on its face. It ranges across a wide swath of forest from the Indian subcontinent through Southeast Asia and southern China. This civet is omnivorous and active at night, foraging for fruit and small animals.",
    life: "10-15 Tahun",
    group: "Mamalia",
    diet: "Buah-buahan & Haiwan Kecil",
    origin: "Asia (Anak Benua India hingga Asia Tenggara)",
    status: "Kurang Membimbangkan",
    fact: "Ia juga digelar 'gem-faced civet' kerana corak topeng unik pada mukanya.",
    image: "Assets/Animals/musang-lamri.jpg"
  },
  "ular-sawa-batik": {
    name: "Ular Sawa Batik",
    scientific: "Malayopython reticulatus",
    descriptionMY: "Ular Sawa Batik ialah spesies ular terpanjang di dunia, dengan sesetengah individu mencecah hampir 10 meter. Ia adalah ular tidak berbisa yang membunuh mangsa dengan melilit dan menyekat pernafasan. Ular ini pandai berenang dan pernah ditemui jauh di lautan terbuka.",
    descriptionEN: "The reticulated python is the longest snake species in the world, with some individuals reaching nearly 10 metres. It is a non-venomous constrictor, killing prey by coiling around it and restricting breathing. This python is an excellent swimmer, sometimes found far out at sea.",
    life: "20-25 Tahun",
    group: "Reptilia",
    diet: "Mamalia & Burung",
    origin: "Asia Selatan & Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Ular Sawa Batik ialah spesies ular terpanjang yang pernah direkodkan di dunia.",
    image: "Assets/Animals/ular-sawa-batik.jpg"
  },
  "memerang-kecil": {
    name: "Memerang Kecil",
    scientific: "Aonyx cinereus",
    descriptionMY: "Memerang Kecil ialah spesies memerang terkecil di dunia. Ia menggunakan cakar depan yang separuh berselaput untuk menggali di lumpur dan mengangkat batu ketika mencari ketam dan siput. Memerang ini hidup dalam kumpulan keluarga besar yang boleh mencecah 12 ekor.",
    descriptionEN: "The Oriental small-clawed otter is the smallest otter species in the world. It uses its partially webbed front paws to dig through mud and lift rocks while hunting for crabs and molluscs. These otters live in large extended family groups of up to a dozen individuals.",
    life: "10-16 Tahun",
    group: "Mamalia",
    diet: "Ikan, Ketam & Kerang",
    origin: "Asia Selatan & Tenggara",
    status: "Terancam (Vulnerable)",
    fact: "Ia adalah spesies memerang terkecil di dunia, memburu menggunakan cakar tangan bukan mulut.",
    image: "Assets/Animals/memerang-kecil.jpg"
  },
  "kambing-pygmy-1": {
    name: "Kambing Pygmy",
    scientific: "Capra aegagrus hircus",
    descriptionMY: "Kambing Pygmy berasal dari kawasan Cameroon di Afrika Barat dan terkenal dengan saiznya yang kecil serta sifatnya yang mesra. Ia adalah haiwan sosial yang hidup dalam kawanan dan gemar memanjat serta melompat ke atas objek. Kambing ini mudah disesuaikan sebagai haiwan pameran mahupun haiwan peliharaan.",
    descriptionEN: "The pygmy goat originates from the Cameroon region of West Africa and is known for its small size and friendly nature. It is a social animal that lives in herds and enjoys climbing and jumping onto objects. Pygmy goats adapt well as both exhibit animals and pets.",
    life: "10-15 Tahun",
    group: "Mamalia",
    diet: "Rumput & Daun",
    origin: "Afrika Barat (Cameroon)",
    status: "Domestik",
    fact: "Walaupun kecil, Kambing Pygmy suka melompat naik ke atas objek dan kenderaan kecil.",
    image: "Assets/Animals/kambing-pygmy.jpg"
  },
  "unta": {
    name: "Unta",
    scientific: "Camelus dromedarius",
    descriptionMY: "Unta berponok tunggal ini sangat disesuaikan dengan kehidupan di kawasan gurun yang kering. Ia boleh bertahan tanpa air selama hampir seminggu, tetapi mampu minum sehingga 145 liter air dalam satu sesi apabila bertemu sumber air. Ponoknya menyimpan lemak, bukan air seperti anggapan umum.",
    descriptionEN: "This one-humped camel is highly adapted to life in dry desert regions. It can survive without water for up to a week, but can drink as much as 145 litres in a single session once it finds a water source. Its hump stores fat, not water as commonly believed.",
    life: "~40 Tahun",
    group: "Mamalia",
    diet: "Rumput & Tumbuhan Berduri",
    origin: "Timur Tengah & Afrika Utara",
    status: "Domestik",
    fact: "Ponok unta menyimpan lemak, bukan air seperti yang selalu disangka ramai.",
    image: "Assets/Animals/unta.jpg"
  },
  "merak-india": {
    name: "Merak India",
    scientific: "Pavo cristatus",
    descriptionMY: "Merak jantan terkenal dengan ekor hiasannya yang boleh mencecah 1.5 meter panjang, dihiasi corak 'mata' berkilauan untuk menarik pasangan. Burung ini merupakan burung kebangsaan India dan tergolong dalam kumpulan omnivor yang turut memakan reptilia kecil dan serangga perosak.",
    descriptionEN: "Male peafowl are famous for their ornamental train, which can reach up to 1.5 metres long and is adorned with shimmering eyespots used to attract mates. This bird is the national bird of India and is omnivorous, also feeding on small reptiles and pest insects.",
    life: "20-25 Tahun",
    group: "Burung",
    diet: "Bijian, Serangga & Reptilia Kecil",
    origin: "Asia Selatan (India)",
    status: "Kurang Membimbangkan",
    fact: "Ekor hiasan merak jantan boleh mencecah 1.5 meter panjang semasa musim mengawan.",
    image: "Assets/Animals/merak-india.jpg"
  },
  "kerbau-albino": {
    name: "Kerbau Albino",
    scientific: "Bubalus bubalis",
    descriptionMY: "Kerbau air biasanya berkulit gelap, namun sebilangan kecil individu albino wujud secara semula jadi dalam populasi kerbau. Kerbau ini penting dalam pertanian Asia sebagai haiwan penarik bajak, dan susunya lebih tinggi lemak berbanding susu lembu biasa.",
    descriptionEN: "Water buffalo usually have dark skin, but a small number of naturally occurring albino individuals exist within buffalo populations. These animals are important in Asian agriculture as draft animals for ploughing, and their milk is richer in fat than cow's milk.",
    life: "15-25 Tahun",
    group: "Mamalia",
    diet: "Rumput",
    origin: "Asia Selatan & Tenggara",
    status: "Domestik",
    fact: "Individu albino seperti ini jarang ditemui secara semula jadi dalam populasi kerbau.",
    image: "Assets/Animals/kerbau-albino.jpg"
  },
  "burung-unta": {
    name: "Burung Unta",
    scientific: "Struthio camelus",
    descriptionMY: "Burung Unta ialah spesies burung terbesar dan tertinggi di dunia, namun tidak boleh terbang. Sebaliknya, kakinya yang panjang dan kuat membolehkannya berlari sehingga 70 km/j, iaitu haiwan berkaki dua terpantas di dunia. Ia menelan batu kecil untuk membantu penghadaman makanan dalam perutnya.",
    descriptionEN: "The ostrich is the largest and tallest bird species in the world, though it cannot fly. Instead, its long, powerful legs let it run up to 70 km/h, making it the fastest two-legged animal on Earth. It swallows small stones to help grind food in its stomach.",
    life: "30-40 Tahun",
    group: "Burung",
    diet: "Rumput, Biji-bijian & Serangga",
    origin: "Afrika",
    status: "Kurang Membimbangkan",
    fact: "Burung Unta ialah haiwan berkaki dua terpantas di dunia, berlari sehingga 70 km/j.",
    image: "Assets/Animals/burung-unta.jpg"
  },
  "black-swan": {
    name: "Black Swan",
    scientific: "Cygnus atratus",
    descriptionMY: "Black Swan terkenal dengan bulu hitamnya yang berkilauan dan paruh merah terang. Ia membentuk ikatan pasangan yang setia sepanjang hayat, sesuatu yang jarang berlaku dalam kalangan burung. Ketibaannya di Eropah pada abad ke-17 mencetuskan idea konsep 'black swan event' kerana ia mencabar kepercayaan bahawa semua angsa berwarna putih.",
    descriptionEN: "The black swan is known for its glossy black plumage and bright red bill. It forms faithful pair bonds that can last a lifetime, a rarity among birds. Its arrival in 17th-century Europe inspired the concept of a 'black swan event', since it challenged the belief that all swans were white.",
    life: "20-40 Tahun",
    group: "Burung",
    diet: "Tumbuhan Akuatik",
    origin: "Australia",
    status: "Kurang Membimbangkan",
    fact: "Penemuan Black Swan di Eropah mencetuskan istilah 'black swan event' yang masih digunakan hari ini.",
    image: "Assets/Animals/black-swan.jpg"
  },
  "landak-raya": {
    name: "Landak Raya",
    scientific: "Hystrix brachyura",
    descriptionMY: "Landak Raya ialah haiwan mengerat besar yang berbadan gempal serta diselubungi duri tajam yang sebenarnya adalah bulu terubah. Ia mampu hidup sehingga 27 tahun dalam penjagaan, jauh lebih lama daripada kebanyakan haiwan mengerat lain. Landak ini aktif pada waktu malam mencari buah-buahan dan akar.",
    descriptionEN: "The Malayan porcupine is a large, stout-bodied rodent covered in sharp quills that are actually modified hairs. It can live up to 27 years in captivity, far longer than most other rodents. This porcupine is nocturnal, foraging for fruit and roots at night.",
    life: "Sehingga 27 Tahun",
    group: "Mamalia",
    diet: "Buah-buahan & Akar",
    origin: "Asia Selatan & Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Duri Landak Raya sebenarnya adalah bulu badan yang telah berubah menjadi tegar dan tajam.",
    image: "Assets/Animals/landak-raya.jpg"
  },
  "ayam-batik": {
    name: "Ayam Batik",
    scientific: "Gallus gallus domesticus (baka Sebright)",
    descriptionMY: "Ayam Batik, atau Sebright, dicipta pada awal abad ke-19 oleh Sir John Sebright melalui pembiakbakaan terpilih ayam bantam hiasan. Namanya dalam Bahasa Melayu diambil sempena corak bulunya yang bertepi gelap menyerupai corak batik. Ia adalah baka ayam pertama yang mempunyai kelab peminat khusus.",
    descriptionEN: "The Sebright, known locally as Ayam Batik, was created in the early 19th century by Sir John Sebright through selective breeding of ornamental bantams. Its Malay name comes from its laced feather pattern, which resembles traditional batik motifs. It was the first chicken breed to have its own dedicated fancier's club.",
    life: "4-8 Tahun",
    group: "Burung",
    diet: "Bijian & Serangga",
    origin: "England",
    status: "Domestik",
    fact: "Nama 'Ayam Batik' diberikan kerana corak bulunya yang menyerupai kain batik tradisional.",
    image: "Assets/Animals/ayam-batik.jpg"
  },
  "iguana": {
    name: "Iguana",
    scientific: "Iguana iguana",
    descriptionMY: "Iguana Hijau adalah herbivor yang memakan daun, bunga dan buah-buahan. Ia adalah perenang yang mahir dan sering melompat ke dalam air dari ketinggian untuk melarikan diri daripada pemangsa. Iguana ini turut membantu penyebaran biji benih di habitat semula jadinya.",
    descriptionEN: "The green iguana is a herbivore that feeds on leaves, flowers, and fruit. It is an excellent swimmer and will often leap into water from great heights to escape predators. Green iguanas also help disperse seeds throughout their natural habitat.",
    life: "10-20 Tahun",
    group: "Reptilia",
    diet: "Daun & Buah-buahan",
    origin: "Amerika Tengah & Selatan",
    status: "Kurang Membimbangkan",
    fact: "Iguana boleh melompat ke dalam air dari ketinggian untuk mengelak pemangsa.",
    image: "Assets/Animals/iguana.jpg"
  },
  "kambing-pygmy-2": {
    name: "Kambing Pygmy",
    scientific: "Capra aegagrus hircus",
    descriptionMY: "Kambing Pygmy berasal dari kawasan Cameroon di Afrika Barat dan terkenal dengan saiznya yang kecil serta sifatnya yang mesra. Ia adalah haiwan sosial yang hidup dalam kawanan dan gemar memanjat serta melompat ke atas objek. Kambing ini mudah disesuaikan sebagai haiwan pameran mahupun haiwan peliharaan.",
    descriptionEN: "The pygmy goat originates from the Cameroon region of West Africa and is known for its small size and friendly nature. It is a social animal that lives in herds and enjoys climbing and jumping onto objects. Pygmy goats adapt well as both exhibit animals and pets.",
    life: "10-15 Tahun",
    group: "Mamalia",
    diet: "Rumput & Daun",
    origin: "Afrika Barat (Cameroon)",
    status: "Domestik",
    fact: "Walaupun kecil, Kambing Pygmy suka melompat naik ke atas objek dan kenderaan kecil.",
    image: "Assets/Animals/kambing-pygmy.jpg"
  },
  "ayam-api": {
    name: "Ayam Api",
    scientific: "Gallus gallus domesticus (baka Phoenix)",
    descriptionMY: "Ayam Api, atau baka Phoenix, dicipta di Jerman pada akhir abad ke-19 dengan membiakbakakan ayam berekor panjang dari Jepun. Namanya sesuai dengan ekornya yang panjang mengalir seperti api atau burung phoenix legenda. Baka ini popular sebagai ayam hiasan di kalangan peminat unggas.",
    descriptionEN: "Ayam Api, or the Phoenix breed, was created in Germany in the late 19th century by cross-breeding long-tailed birds imported from Japan. Its name fits its flowing, flame-like tail reminiscent of the legendary phoenix. This breed is popular among poultry fanciers as an ornamental chicken.",
    life: "6-8 Tahun",
    group: "Burung",
    diet: "Bijian & Serangga",
    origin: "Jerman (berasal dari baka Jepun)",
    status: "Domestik",
    fact: "Ekornya yang panjang mengalir menjadikannya dinamakan sempena burung phoenix legenda.",
    image: "Assets/Animals/ayam-api.jpg"
  },
  "kambing": {
    name: "Kambing",
    scientific: "Capra aegagrus hircus",
    descriptionMY: "Kambing merupakan salah satu haiwan pertama yang didomestikasi oleh manusia, hampir 10,000 tahun dahulu di Timur Tengah. Ia adalah haiwan pemamah biak yang mampu mencerna pelbagai jenis tumbuhan berserat. Kambing dipelihara secara meluas untuk susu, daging, bulu dan kulit.",
    descriptionEN: "The goat is one of the earliest animals domesticated by humans, nearly 10,000 years ago in the Middle East. It is a ruminant capable of digesting a wide variety of fibrous plants. Goats are widely kept for milk, meat, fibre, and hide.",
    life: "15-18 Tahun",
    group: "Mamalia",
    diet: "Rumput & Daun",
    origin: "Timur Tengah",
    status: "Domestik",
    fact: "Kambing antara haiwan pertama yang didomestikasi manusia, hampir 10,000 tahun lalu.",
    image: "Assets/Animals/kambing.jpg"
  },
  "meerkat": {
    name: "Meerkat",
    scientific: "Suricata suricatta",
    descriptionMY: "Meerkat hidup dalam kumpulan besar dan bekerjasama menjaga anak serta mengawasi pemangsa dengan berdiri tegak di atas kaki belakang. Ia kebal terhadap bisa kala jengking, membolehkannya memburu haiwan berbahaya ini tanpa risiko. Corak gelap di sekeliling matanya membantu mengurangkan silauan cahaya matahari padang pasir.",
    descriptionEN: "Meerkats live in large groups, cooperatively raising pups and watching for predators by standing upright on their hind legs. They are immune to scorpion venom, allowing them to hunt these dangerous creatures without risk. The dark patches around their eyes help reduce glare from the desert sun.",
    life: "10-14 Tahun",
    group: "Mamalia",
    diet: "Serangga & Invertebrata",
    origin: "Afrika Selatan",
    status: "Kurang Membimbangkan",
    fact: "Meerkat kebal terhadap bisa kala jengking, membolehkannya memburu haiwan ini tanpa risiko.",
    image: "Assets/Animals/meerkat.jpg"
  },
  "rusa-timorensis": {
    name: "Rusa Timorensis",
    scientific: "Rusa timorensis",
    descriptionMY: "Rusa Timorensis, atau Rusa Sunda, berasal dari kepulauan Indonesia termasuk Jawa, Bali dan Timor. Hanya rusa jantan yang memiliki tanduk berbentuk lira dengan tiga cabang. Ia hidup dalam kumpulan kecil dan menjadi mangsa utama harimau, ular sawa serta buaya di habitat asalnya.",
    descriptionEN: "The Javan rusa, or Sunda sambar, is native to the Indonesian islands including Java, Bali, and Timor. Only males carry lyre-shaped, three-tined antlers. It lives in small groups and is preyed on by tigers, pythons, and crocodiles in its native range.",
    life: "15-20 Tahun",
    group: "Mamalia",
    diet: "Rumput & Daun",
    origin: "Indonesia (Jawa, Bali, Timor)",
    status: "Terancam (Vulnerable)",
    fact: "Hanya rusa jantan Rusa Timorensis yang memiliki tanduk berbentuk lira tiga cabang.",
    image: "Assets/Animals/rusa-timorensis.jpg"
  },
  "rusa-axis": {
    name: "Rusa Axis",
    scientific: "Axis axis",
    descriptionMY: "Rusa Axis, atau Chital, mengekalkan corak bintik putihnya sepanjang hayat, tidak seperti kebanyakan spesies rusa lain yang kehilangan bintik apabila dewasa. Ia sering bergaul dengan kera langur, memanfaatkan amaran bahaya kera tersebut serta buah yang dijatuhkan dari pokok.",
    descriptionEN: "The chital, or axis deer, retains its white-spotted coat throughout its life, unlike most other deer species that lose their spots as they mature. It often associates with langur monkeys, benefiting from their alarm calls and the fruit they drop from trees.",
    life: "15-20 Tahun",
    group: "Mamalia",
    diet: "Rumput Pendek & Daun",
    origin: "Anak Benua India",
    status: "Kurang Membimbangkan",
    fact: "Rusa Axis mengekalkan corak bintik putihnya sepanjang hayat, tidak seperti kebanyakan rusa lain.",
    image: "Assets/Animals/rusa-axis.jpg"
  },
  "angsa": {
    name: "Angsa",
    scientific: "Anser anser domesticus",
    descriptionMY: "Angsa peliharaan diturunkan daripada angsa liar Greylag yang telah didomestikasi lebih 3,000 tahun lalu di Mesir purba. Angsa terkenal sebagai penjaga yang agresif dan telah digunakan sebagai 'anjing peronda' semenjak zaman purba kerana bunyi bising dan sifat protektifnya.",
    descriptionEN: "The domestic goose is descended from the wild greylag goose, domesticated over 3,000 years ago in ancient Egypt. Geese are known as aggressive guardians and have been used as 'watch geese' since ancient times because of their loud honking and protective nature.",
    life: "15-25 Tahun",
    group: "Burung",
    diet: "Rumput & Bijian",
    origin: "Eropah & Asia",
    status: "Domestik",
    fact: "Angsa telah digunakan sebagai 'penjaga' sejak zaman purba kerana sifatnya yang protektif.",
    image: "Assets/Animals/angsa.jpg"
  },
  "ferret": {
    name: "Ferret",
    scientific: "Mustela putorius furo",
    descriptionMY: "Ferret ialah bentuk domestikasi daripada polecat Eropah, dan telah dipelihara manusia sejak kira-kira 2,500 tahun lalu. Ia mempunyai badan panjang dan lentur yang sesuai untuk masuk ke dalam lubang sempit, satu ciri yang menjadikannya digunakan untuk memburu arnab pada zaman dahulu.",
    descriptionEN: "The ferret is a domesticated form of the European polecat and has been kept by humans for around 2,500 years. It has a long, flexible body suited for squeezing through narrow burrows, a trait once used for hunting rabbits.",
    life: "7-10 Tahun",
    group: "Mamalia",
    diet: "Daging",
    origin: "Eropah (didomestikasi daripada polecat)",
    status: "Domestik",
    fact: "Badan Ferret yang panjang dan lentur pernah digunakan untuk memburu arnab dalam lubang.",
    image: "Assets/Animals/ferret.jpg"
  },
  "itik-belibis": {
    name: "Itik Belibis",
    scientific: "Dendrocygna javanica",
    descriptionMY: "Itik Belibis dikenali dengan bunyi siulan dua nada yang khas semasa terbang. Ia sering berkumpul di kawasan sawah padi dan tasik pada waktu siang, tetapi lebih aktif mencari makan pada waktu malam. Itik ini juga boleh bertenggek di atas dahan pokok, tidak seperti kebanyakan itik lain.",
    descriptionEN: "The lesser whistling duck is known for its distinctive two-note wheezy whistle in flight. It often gathers in flocks around lakes and paddy fields during the day but is more active feeding at night. This duck can also perch on tree branches, unlike most other ducks.",
    life: "~10 Tahun",
    group: "Burung",
    diet: "Bijian & Tumbuhan Akuatik",
    origin: "Asia Selatan & Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Berbeza dengan itik lain, Itik Belibis boleh bertenggek dan bersarang di atas pokok.",
    image: "Assets/Animals/itik-belibis.jpg"
  },
  "ikan-koi": {
    name: "Ikan Koi",
    scientific: "Cyprinus carpio",
    descriptionMY: "Ikan Koi ialah varieti ikan mas hiasan yang dibiakkan secara terpilih oleh petani Jepun sejak abad ke-19 untuk mendapatkan corak warna yang menarik. Ia boleh hidup sehingga puluhan tahun dengan penjagaan yang baik, dan sering dikaitkan dengan tuah, ketabahan serta kejayaan dalam budaya Asia.",
    descriptionEN: "Koi are ornamental varieties of common carp, selectively bred by Japanese farmers since the 19th century for their striking color patterns. With good care they can live for decades, and in Asian culture they are often associated with good fortune, perseverance, and success.",
    life: "25-50+ Tahun",
    group: "Ikan",
    diet: "Pelet & Tumbuhan Air",
    origin: "Jepun",
    status: "Domestik",
    fact: "Dengan penjagaan yang baik, sesetengah Ikan Koi boleh hidup lebih 50 tahun.",
    image: "Assets/Animals/ikan-koi.jpg"
  },
  "burung-hantu-kuning": {
    name: "Burung Hantu Kuning",
    scientific: "Ketupa ketupu",
    descriptionMY: "Burung Hantu Kuning, atau Buffy Fish Owl, memburu terutamanya ikan dari tepi sungai atau tasik, selain memakan ketam dan haiwan kecil lain. Ia sering hinggap di dahan berhampiran air pada waktu malam, menunggu peluang untuk menyambar mangsa dari permukaan air.",
    descriptionEN: "The buffy fish owl hunts mainly fish from the water's edge, as well as crabs and other small animals. It often perches on branches near water at night, waiting for the chance to snatch prey from the water's surface.",
    life: "10-15 Tahun",
    group: "Burung",
    diet: "Ikan & Haiwan Kecil",
    origin: "Asia Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Berbeza daripada burung hantu lain, Burung Hantu Kuning lebih gemar memburu ikan.",
    image: "Assets/Animals/burung-hantu-kuning.jpg"
  },
  "burung-lang-hantu": {
    name: "Burung Lang Hantu",
    scientific: "Nisaetus alboniger",
    descriptionMY: "Burung Lang Hantu ialah helang bersaiz sederhana yang mendiami hutan Semenanjung Malaysia, Sumatra dan Borneo. Ia memburu dengan melayang tinggi di atas kanopi hutan sebelum menukik menangkap mamalia kecil, burung dan kadangkala unggas ternakan.",
    descriptionEN: "Blyth's hawk-eagle is a medium-sized eagle found in the forests of the Malay Peninsula, Sumatra, and Borneo. It hunts by circling high over the forest canopy before swooping down to catch small mammals, birds, and occasionally poultry.",
    life: "15-20 Tahun",
    group: "Burung",
    diet: "Mamalia Kecil & Burung",
    origin: "Semenanjung Malaysia, Sumatra & Borneo",
    status: "Kurang Membimbangkan",
    fact: "Namanya diambil sempena ahli zoologi Edward Blyth yang pertama menemuinya di Melaka.",
    image: "Assets/Animals/burung-lang-hantu.jpg"
  },
  "kuda-padi": {
    name: "Kuda Padi",
    scientific: "Equus caballus (baka mini)",
    descriptionMY: "Kuda Padi merujuk kepada baka kuda mini yang bersaiz kecil tetapi mengekalkan perkadaran badan seperti kuda biasa. Baka seperti Falabella dari Argentina terkenal dengan jangka hayat yang panjang berbanding kuda bersaiz penuh, sesetengah hidup melebihi 40 tahun.",
    descriptionEN: "'Kuda Padi' refers to miniature horse breeds that are small in stature but retain the body proportions of a full-sized horse. Breeds such as the Falabella from Argentina are notable for their unusually long lifespans compared to full-sized horses, with some living beyond 40 years.",
    life: "25-30 Tahun",
    group: "Mamalia",
    diet: "Rumput & Jerami",
    origin: "Pelbagai (baka kuda mini)",
    status: "Domestik",
    fact: "Sesetengah baka kuda mini seperti Falabella boleh hidup melebihi 40 tahun.",
    image: "Assets/Animals/kuda-padi.jpg"
  },
  "lembu-bali-rusa-timorensis": {
    name: "Lembu Bali",
    scientific: "Bos javanicus domesticus",
    descriptionMY: "Lembu Bali ialah keturunan domestikasi banteng liar, dan menjadi sumber daging serta haiwan penarik bajak yang penting di Indonesia. Ia mempunyai tompok putih ciri khas di bahagian punggung dan kaki, dengan warna badan kemerahan pada betina dan gelap kecoklatan pada jantan dewasa.",
    descriptionEN: "Bali cattle are a domesticated form of the wild banteng and serve as an important source of meat and draft power for ploughing in Indonesia. They have a characteristic white rump patch and white stockings, with females reddish-yellow and mature males turning dark brown.",
    life: "15-20 Tahun",
    group: "Mamalia",
    diet: "Rumput & Pucuk Muda",
    origin: "Indonesia (Bali)",
    status: "Domestik",
    fact: "Lembu Bali diturunkan daripada banteng liar yang kini tergolong terancam di alam liar.",
    image: "Assets/Animals/lembu-bali.jpg"
  },
  "murai-batu": {
    name: "Murai Batu",
    scientific: "Copsychus malabaricus",
    descriptionMY: "Murai Batu terkenal dengan nyanyian merdu dan ekor panjang yang mengalir, menjadikannya salah satu burung paling digemari dalam pertandingan burung berkicau di Asia Tenggara. Jantan berwarna hitam berkilat dengan dada berwarna kastanya, manakala betina lebih kelabu dan berekor lebih pendek.",
    descriptionEN: "The white-rumped shama is renowned for its melodious song and long, flowing tail, making it one of the most prized birds in Southeast Asian songbird competitions. Males are glossy black with a chestnut chest, while females are greyer with shorter tails.",
    life: "10-15 Tahun",
    group: "Burung",
    diet: "Serangga",
    origin: "Asia Selatan & Tenggara",
    status: "Kurang Membimbangkan",
    fact: "Nyanyiannya yang merdu menjadikan Murai Batu sangat digemari dalam pertandingan burung berkicau.",
    image: "Assets/Animals/murai-batu.jpg"
  },
  "red-crimson": {
    name: "Red Crimson",
    scientific: "Neochmia phaeton",
    descriptionMY: "Red Crimson, atau Crimson Finch, ialah burung kecil berwarna merah menyala yang berasal dari kawasan utara Australia. Ia agak agresif terhadap burung lain yang berwarna merah, terutamanya semasa musim mengawan, dan sering ditemui berhampiran kawasan tebing sungai berumput panjang.",
    descriptionEN: "The crimson finch is a small, brilliantly red-plumaged bird native to northern Australia. It can be quite aggressive toward other red-plumaged birds, especially during breeding season, and is often found near riverbanks lined with long grass.",
    life: "5-6 Tahun",
    group: "Burung",
    diet: "Biji Rumput & Serangga",
    origin: "Australia",
    status: "Kurang Membimbangkan",
    fact: "Nama gelarannya 'killer finch' datang daripada sikapnya yang agresif terhadap burung berwarna merah lain.",
    image: "Assets/Animals/red-crimson.jpg"
  },
  "love-bird": {
    name: "Love Bird",
    scientific: "Agapornis roseicollis",
    descriptionMY: "Love Bird terkenal dengan tabiat tidurnya yang unik iaitu duduk berdempet sesama pasangan sambil menghadap muka masing-masing, yang mengilhamkan nama 'burung cinta'. Ia adalah burung yang sangat sosial dan bersuara nyaring, sering ditemui dalam kumpulan kecil di alam liar Afrika.",
    descriptionEN: "Lovebirds are famous for their unique sleeping habit of sitting side by side with mates and turning their faces toward each other, which inspired their name. They are highly social, loudly vocal birds, often found in small flocks in the wild in Africa.",
    life: "10-15 Tahun",
    group: "Burung",
    diet: "Bijian & Buah-buahan",
    origin: "Afrika Selatan Barat (Namibia & Angola)",
    status: "Kurang Membimbangkan",
    fact: "Nama 'burung cinta' datang daripada tabiatnya duduk berdempet menghadap pasangan semasa tidur.",
    image: "Assets/Animals/love-bird.jpg"
  },
  "budgies-bird": {
    name: "Budgies Bird",
    scientific: "Melopsittacus undulatus",
    descriptionMY: "Budgerigar ialah burung nuri kecil yang berasal dari kawasan pedalaman kering Australia, di mana ia hidup secara nomad mengikut sumber air dan makanan. Ia adalah antara haiwan peliharaan paling popular di dunia, terkenal dengan kebolehannya meniru pertuturan manusia.",
    descriptionEN: "The budgerigar is a small parakeet native to the dry interior of Australia, where it lives a nomadic lifestyle following water and food sources. It is among the most popular pets in the world, well known for its ability to mimic human speech.",
    life: "5-10 Tahun",
    group: "Burung",
    diet: "Biji Rumput",
    origin: "Australia",
    status: "Kurang Membimbangkan",
    fact: "Budgerigar dianggarkan antara haiwan peliharaan ketiga paling popular di dunia selepas kucing dan anjing.",
    image: "Assets/Animals/budgies.jpg"
  },
  "strawberry-finch-bird": {
    name: "Strawberry Finch Bird",
    scientific: "Amandava amandava",
    descriptionMY: "Strawberry Finch, atau Red Avadavat, mendapat namanya daripada bulu merah menyala berbintik putih yang muncul pada jantan semasa musim mengawan. Burung kecil ini hidup berkawan dalam kumpulan besar di padang rumput terbuka dan sawah padi di Asia Selatan.",
    descriptionEN: "The strawberry finch, or red avadavat, gets its name from the vivid red, white-spotted plumage males develop during the breeding season. This small bird lives gregariously in large flocks across open grasslands and paddy fields in South Asia.",
    life: "7-8 Tahun",
    group: "Burung",
    diet: "Biji Rumput & Serangga",
    origin: "Asia Selatan",
    status: "Kurang Membimbangkan",
    fact: "Bulu merah menyala jantan hanya muncul semasa musim mengawan sahaja.",
    image: "Assets/Animals/strawberry-finch.jpg"
  },
  "lembu-limbousim-lembu-kampung": {
    name: "Lembu Limousin / Lembu Kampung",
    scientific: "Bos taurus",
    descriptionMY: "Lembu Limousin berasal dari daerah Limousin di Perancis dan terkenal sebagai baka lembu daging berkualiti tinggi. Ia sering dibandingkan dengan Lembu Kampung tempatan yang lebih kecil namun tahan lasak terhadap cuaca panas dan lembap di Asia Tenggara.",
    descriptionEN: "The Limousin is a cattle breed from the Limousin region of France, prized as a high-quality beef breed. It is often compared here with the smaller local Kampung cattle, which are hardier and better adapted to the hot, humid climate of Southeast Asia.",
    life: "15-20 Tahun",
    group: "Mamalia",
    diet: "Rumput",
    origin: "Perancis (Limousin) & Tempatan",
    status: "Domestik",
    fact: "Lembu Kampung tempatan lebih tahan lasak terhadap cuaca panas berbanding baka Eropah seperti Limousin.",
    image: "Assets/Animals/lembu-limousin.jpg"
  },
  "sulcata-tortoise": {
    name: "Sulcata Tortoise",
    scientific: "Centrochelys sulcata",
    descriptionMY: "Sulcata Tortoise ialah kura-kura darat ketiga terbesar di dunia dan boleh hidup lebih 70 tahun, menjadikannya salah satu haiwan pameran paling tahan lama. Ia menggali lubang dalam untuk berlindung daripada panas terik Gurun Sahara pada waktu siang.",
    descriptionEN: "The African spurred tortoise is the third-largest tortoise species in the world and can live beyond 70 years, making it one of the longest-lived exhibit animals. It digs deep burrows to shelter from the intense heat of the Sahara during the day.",
    life: "50-100+ Tahun",
    group: "Reptilia",
    diet: "Rumput & Tumbuhan",
    origin: "Gurun Sahara, Afrika",
    status: "Terancam (Vulnerable)",
    fact: "Sulcata Tortoise boleh hidup lebih lama daripada manusia, ada rekod mencecah lebih 70 tahun.",
    image: "Assets/Animals/sulcata-tortoise.jpg"
  },
};

function _stub(name) {
  return {
    name: name,
    scientific: "",
    descriptionMY: "Akan datang.",
    descriptionEN: "Coming soon.",
    life: "-",
    group: "-",
    diet: "-",
    origin: "-",
    status: "-",
    fact: "-",
    image: "Assets/Animals/placeholder.jpg"
  };
}
